### PR TITLE
feature/packaging

### PR DESCRIPTION
**Pull request by apiad**
I went ahead and tried to refactor the project for easier packaging. That involved actually creating a Python package named `konverter` with an `__init__.py` and refactoring the imports inside the previous .py scripts (i.e., stuff in utils).

I also added Poetry as a dependency manager and packaging solution. I find Poetry much better than Pipenv and alternatives, but it is a matter of taste, so you could definitely want a different solution. 

The whole pull request, in general, does the following:

1) Now there is a pyproject.toml file with the package info.
2) The whole code is now in the `konverter` folder, there is no longer a konverter.py file standing outside and the code that was there is now in `konverter/__init__.py`
3) To use it, now you should invoke `python -m konverter <INPUT> <OUTPUT>` instead of manually replacing the input and output inside the source file. The code for this part is in `konverter/__main__.py`
4) Developers now should install Poetry (https://python-poetry.org/docs/#installation) to keep their virtual environments up to date. This is necessary so every developer has the same dependencies, instead of trusting everyone has the right libraries in their system's Python.
5) To package, run `poetry build` and to publish run `poetry publish`, make sure to have a Pypi account created and input your credentials. I didn't want to create the package myself in Pypi because I think the @ShaneSmiskol should be the official package owner.

@ShaneSmiskol, I don't necessarily think you should merge this right now, but rather check it out in a different branch and let me know if/what you would like to change and let's work from there.

Regards,
Alejandro

### CODE REVIEW

**Comment by ShaneSmiskol** [comment]
Could you re-open a new PR for the new branch I created for you? It's the same name as your branch. Thanks for the PR! Looks like some good stuff

**Comment by ShaneSmiskol** [comment]
Thanks for the PR! Everything looks good! I haven't use Poetry at all but are all those dependencies really required? For example google-auth, requests, etc

**Comment by apiad** [comment]
Hey, glad you like it. Regarding the dependencies, the only **required** direct dependencies of the project are listed in `pyproject.toml`, and they are:

* `typer = "^0.1.1"`: for the CLI, not really necessary for its nice to use...
* `numpy = "^1.18.3"`: I guess this one is mandatory.

Most of the dependencies you see are dev dependencies, so only if you are a developer of the project you would install those. Someone simply `pip install`ing the project would not get them. You can try this on a clean virtualenv to directly see what get's installed. Most of those dependencies are actually development dependencies of `tensorflow`, by the way, which is a beast, as you probable know already.

I opted to put `tensorflow` as a dev dependency to make sure that all developers have it, but not force the user of the library to download `tensorflow` when installing `konverter`. I mean, as a user, if you already don't have `tensorflow` then you probably don't even know what to do with this library, and I wouldn't like to dump all of those dependencies on someone who is just exploring. Hence, even if it might not be the most recommended way, I think as a user I prefer for `konverter` to scream at me saying I'm missing `tensorflow` than inadvertently downloading and installing all that stuff. We can do the same with `numpy` if you prefer, I just felt it was small and core enough to deserve being a core dependency. Anyway, It's your call.

**Comment by apiad** [comment]
I think the next step would be to actually set up testing (I added `pytest` to the dependencies but there is no actual testing code yet) and then set up Github to run a couple of minimal tests: some basic unit tests for your layers and models, and maybe one integration test to create a blank slate environment in install the package, just to see if the installation is smooth.

**Comment by ShaneSmiskol** [comment]
Ah okay, I haven't ever built a package that was designed to be installed by users, so this is all new to me. Thanks for clearing it up then. It looks good then, I think I'll merge it tonight and start working on adding tests and cleaning up Konverter further tomorrow. My goal is to let users add new layers only by editing model_attributes.py with no changes to konverter.py, or now konverter/__init__.py! But there's still some custom stuff in the Konverter class to allow it to work, so that will come soon.

**Comment by ShaneSmiskol** [comment]
Thanks for the PR again! So with GitHub Actions, it's possible to define a list of files needed to create a PyPi release and it would automatically create them when committed to a release branch or something similar?

**Comment by apiad** [comment]
Actually I think it will end up being easier than that. When you run `poetry build` you already obtain the bundled package, and `poetry publish` connects to PyPi and all, so all you would need is to supply your PyPi credentials somehow to Github Actions (there must be some way of doing it without sharing them publicly). 

I have done this before with Travis CI which is an independent continuous integration platform that integrates with Github and you can run tests and do a bunch of stuff automatically on every commit, PR, etc., including `poetry publish`. I haven't done it with Github Actions but I'm eager to try it because I like the idea of keeping things inside Github and not using external services unless critically necessary. So I will explore that idea next. 

The roadmap, in my opinion, would be something like this, which is what I often do in my projects:
1) Whenever someone pushes a commit, PR, etc., Github Actions kicks in and runs all the tests (which ideally should cover most cases, but we know, real life is a bummer). If tests don't pass you will see it in the PR and ideally even right there see which test failed, down to line number and all. It will not let you merge PRs with failing tests either.
2) If the commit is a release commit (i.e., it has a tag version associated), then in addition to running all tests, the packaging task kicks in and publishes to PyPi (on successful testing, of course). 

As I said, I've done this with Travis CI before and it's not very hard, it's just a matter of configuring some yamls here and there, but I haven't done it with Github Actions, though I'm guessing it must be quite similar.

**Comment by ShaneSmiskol** [comment]
I've used Travis CI before to verify my commits of a fork of another piece of software but never set up my own tests so I'm exciting to get a hand at trying that finally. Excellent, I'll look into Poetry a bit more soon. I'll let you know how far I get with Actions, I think I'll write some tests and try one

**Comment by apiad** [comment]
Awesome, I'll take some time later to look into Github Actions as well, so I guess we'll share battle stories afterwards :smile:

**Comment by ShaneSmiskol** [comment]
Okay, I understand how Poetry works now with its dependencies. I read some comments from people on the Poetry repo saying how atrocious pipenv is. I haven't used either before this, but I gotta say Poetry is quite elegant!

I think I almost have the Actions set up to work with the test I have written. I'm just running into weird issues where TensorFlow with Windows and MacOS is throwing errors that it shouldn't, as well as `2.1.0` not being available but `2.1.0.b` works fine on Ubuntu. I guess it'll be fine for now!

**Comment by apiad** [comment]
I also have run into some problems before with Poetry and TF, in other projects. In part for that reason is that I think this project shouldn't specifically depend on TF, instead, I think the user should independently install TF and if the version he/she has is incompatible with `konverter`, then I guess it's bad luck, but I don't see someone changing their TF version to be compatible with `konverter`, honestly, neither I see how someone would want to use `konverter` and still don't know what TF is or having installed it.

For these reasons, I think TF should not be a dependency of `konverter`, but I think you should keep it in the dev dependencies so that you can use it in testing. Anyway, that's my two cents of course, it's your call :smile:

**Pull request merged**
