### PR TITLE
Add working GitHub Actions support

### PR DESCRIPTION
**Pull request by ShaneSmiskol**
Tests one model architecture and gives us a nice little green tick if the errors between the Keras model and the Konverted model are low enough!

### CODE REVIEW

**Comment by apiad** [comment]
Kudos on this! I skimmed over the `test.yml` and I'm really impressed by the apparent complexity and completeness of it. I have never used Github Actions before so I'm learning by example here. I'll pull from this and test on my end and let you know if I come up with some ideas.

Keep up the great work!!

**Comment by ShaneSmiskol** [comment]
Thank you! I really just copied the example code from Poetry so that I could use the correct implementation and the rest of the commits were just getting the matrix to work properly, adding custom versions of TF based on the Python version as well as fixing issues with Poetry and TensorFlow which I just decided on using pip itself for the tests in the end haha. I hope it helps, you could really cut out a few steps if you don't need cache, but that seems to speed it up quite a bit

**Comment by ShaneSmiskol** [comment]
Do you have Discord? I'm having some trouble with Typer, you probably know more about it

**Comment by apiad** [comment]
As of 5 minutes ago, I do, my username is `apiad#1042`.

**Comment by apiad** [comment]
I don't think Typer is all that important here, since `konverter` doesn't (yet) have a complicated CLI, so if it is causing problems, I think a pure `argparse` rewrite is fairly easy. I can do it if you want.

**Pull request merged**
